# Generated by Django 2.0 on 2018-05-31 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import organs.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonOrgan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('organ_name', models.CharField(default='', max_length=100, verbose_name='企业/组织名称')),
                ('organ_scale', models.SmallIntegerField(blank=True, choices=[(1, '0-49人'), (2, '50-199人'), (3, '200-499人'), (4, '500-999人'), (5, '1000-1999人'), (6, '2000人以上')], default=1, null=True, verbose_name='企业规模')),
                ('contact_name', models.CharField(default='', max_length=32, verbose_name='联系人姓名')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='联系人手机号码')),
                ('contact_title', models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='联系人职位')),
                ('logo', models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='企业logo')),
                ('industry', models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='行业类型')),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='企业/机构地址')),
                ('contact', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='联系电话')),
                ('auth_status', models.SmallIntegerField(choices=[(1, '等待审核'), (2, '审核通过'), (3, '审核未通过')], default=1, verbose_name='认证状态')),
                ('media_cover', models.CharField(blank=True, default='', max_length=800, null=True, verbose_name='媒体报道')),
                ('desc', models.TextField(blank=True, default='', null=True, verbose_name='企业介绍')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': 'A 企业/组织',
                'verbose_name_plural': 'A 企业/组织',
                'db_table': 'organs_organ',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=255, verbose_name='权限名')),
                ('codename', models.CharField(max_length=100, verbose_name='权限码')),
                ('pre_defined', models.BooleanField(default=False, verbose_name='平台预定义')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'db_table': 'perm_permission',
                'ordering': ('codename',),
            },
            managers=[
                ('objects', organs.managers.PermissionManager()),
            ],
        ),
        migrations.CreateModel(
            name='StaffSecureRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('key', models.CharField(max_length=128)),
                ('expire_datetime', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
