# Generated by Django 2.0 on 2018-10-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': '文件', 'verbose_name_plural': '文件'},
        ),
        migrations.RemoveField(
            model_name='file',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='file',
            name='uuid_name',
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=128, verbose_name='文件名称'),
        ),
    ]
