# Generated by Django 2.0 on 2018-06-06 15:20

from django.db import migrations, models
import django.db.models.deletion
from settings.subs.init_data_conf import SET_PROJECT_START_ID


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('title', models.CharField(max_length=10, verbose_name='里程碑标题')),
                ('index', models.SmallIntegerField(default=1, verbose_name='索引顺序')),
                ('desc', models.CharField(default='', max_length=20, verbose_name='描述')),
            ],
            options={
                'verbose_name': '里程碑项',
                'verbose_name_plural': '里程碑项',
                'db_table': 'projects_milestone',
            },
        ),
        migrations.CreateModel(
            name='ProjectFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('title', models.CharField(default='默认', max_length=30, verbose_name='流程名称')),
                ('type', models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='流程类型')),
                ('pre_defined', models.BooleanField(default=False, verbose_name='是否预定义')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.Hospital', verbose_name='所属医院')),
            ],
            options={
                'verbose_name': '项目流程',
                'verbose_name_plural': '项目流程',
                'db_table': 'projects_project_flow',
            },
        ),
        migrations.CreateModel(
            name='ProjectPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('title', models.CharField(max_length=30, verbose_name='项目名称')),
                ('purpose', models.CharField(default='', max_length=100, null=True, verbose_name='申请原因')),
                ('status', models.CharField(choices=[('PE', '未开始'), ('SD', '已启动'), ('DO', '已完成')], default='PE', max_length=2, verbose_name='项目状态')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to='hospitals.Staff', verbose_name='项目申请人/提出者')),
                ('current_stone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Milestone', verbose_name='项目里程碑结点')),
                ('performer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_projects', to='hospitals.Staff', verbose_name='项目负责人/执行人')),
                ('related_dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitals.Department', verbose_name='申请科室')),
            ],
            options={
                'verbose_name': '采购申请/项目计划',
                'verbose_name_plural': '采购申请',
                'db_table': 'projects_project_plan',
            },
        ),
        migrations.AddField(
            model_name='milestone',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectFlow', verbose_name='归属流程'),
        ),

        # customized id start
        migrations.RunSQL(  # id自增从设定的值开始
            SET_PROJECT_START_ID,
        ),
    ]
