# Generated by Django 2.0 on 2018-06-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectflow',
            options={'verbose_name': 'B 项目流程', 'verbose_name_plural': 'B 项目流程'},
        ),
        migrations.AlterModelOptions(
            name='projectplan',
            options={'verbose_name': 'A 项目申请', 'verbose_name_plural': 'A 项目申请'},
        ),
        migrations.AddField(
            model_name='projectplan',
            name='expired_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='项目截止时间'),
        ),
        migrations.AddField(
            model_name='projectplan',
            name='startup_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='项目启动时间'),
        ),
    ]
