# Generated by Django 2.0 on 2018-07-24 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_auto_20180724_1810'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMilestoneRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '项目里程碑记录',
                'verbose_name_plural': '项目里程碑记录',
                'db_table': 'projects_project_milestone_record',
            },
        ),
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['index'], 'verbose_name': '里程碑项', 'verbose_name_plural': '里程碑项'},
        ),
        migrations.AlterModelOptions(
            name='projectflow',
            options={'verbose_name': 'B 项目流程', 'verbose_name_plural': 'B 项目流程'},
        ),
        migrations.AlterModelOptions(
            name='projectplan',
            options={'verbose_name': 'A 项目申请', 'verbose_name_plural': 'A 项目申请'},
        ),
        migrations.RenameField(
            model_name='projectflow',
            old_name='hospital',
            new_name='organ',
        ),
        migrations.AddField(
            model_name='projectplan',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_projects', to='hospitals.Staff', verbose_name='协助办理人'),
        ),
        migrations.AddField(
            model_name='projectplan',
            name='attached_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.ProjectFlow', verbose_name='项目使用的流程'),
        ),
        migrations.AddField(
            model_name='projectplan',
            name='expired_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='项目截止时间'),
        ),
        migrations.AddField(
            model_name='projectplan',
            name='handing_type',
            field=models.CharField(choices=[('SE', '自行办理'), ('AG', '转交办理')], default='SE', max_length=2, verbose_name='办理方式'),
        ),
        migrations.AddField(
            model_name='projectplan',
            name='project_cate',
            field=models.CharField(choices=[('SW', '信息化项目'), ('HW', '医疗器械项目')], default='HW', max_length=2, verbose_name='项目类型'),
        ),
        migrations.AddField(
            model_name='projectplan',
            name='startup_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='项目启动时间'),
        ),
        migrations.AddField(
            model_name='projectmilestonerecord',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Milestone', verbose_name='里程碑节点'),
        ),
        migrations.AddField(
            model_name='projectmilestonerecord',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectPlan', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='projectplan',
            name='milestones',
            field=models.ManyToManyField(blank=True, related_name='projects', related_query_name='project', through='projects.ProjectMilestoneRecord', to='projects.Milestone', verbose_name='里程碑轨迹'),
        ),
    ]
