# Generated by Django 2.0 on 2018-06-22 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180621_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectplan',
            name='attached_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.ProjectFlow', verbose_name='项目使用的流程'),
        ),
    ]
