# Generated by Django 2.0 on 2018-08-28 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180724_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='parent_milestone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Milestone'),
        ),
        migrations.AddField(
            model_name='projectflow',
            name='default_flow',
            field=models.BooleanField(default=True, verbose_name='是否为默认流程'),
        ),
        migrations.AddField(
            model_name='projectmilestonerecord',
            name='doc_list',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='文档列表'),
        ),
        migrations.AddField(
            model_name='projectmilestonerecord',
            name='summary',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='总结说明'),
        ),
        migrations.AddField(
            model_name='projectplan',
            name='estimate_total_price',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='项目预估总价'),
        ),
        migrations.AddField(
            model_name='projectplan',
            name='procurement_method',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='采购方法'),
        ),
        migrations.AddField(
            model_name='projectplan',
            name='project_introduce',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='项目介绍/项目描述'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.ProjectFlow', verbose_name='归属流程'),
        ),
        migrations.AlterField(
            model_name='projectmilestonerecord',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_milestone_records', to='projects.Milestone', verbose_name='里程碑节点'),
        ),
        migrations.AlterField(
            model_name='projectmilestonerecord',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_milestone_records', to='projects.ProjectPlan', verbose_name='项目'),
        ),
    ]
