# Generated by Django 2.0 on 2018-08-21 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180724_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.ProjectFlow', verbose_name='归属流程'),
        ),
        migrations.AlterField(
            model_name='projectmilestonerecord',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_milestone_records', to='projects.Milestone', verbose_name='里程碑节点'),
        ),
        migrations.AlterField(
            model_name='projectmilestonerecord',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_milestone_records', to='projects.ProjectPlan', verbose_name='项目'),
        ),
    ]
