# Generated by Django 2.0 on 2018-06-22 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectplan_attached_flow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['index'], 'verbose_name': '里程碑项', 'verbose_name_plural': '里程碑项'},
        ),
        migrations.RenameField(
            model_name='projectflow',
            old_name='hospital',
            new_name='organ',
        ),
    ]
