# Generated by Django 2.0 on 2018-08-28 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180828_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectplan',
            old_name='estimate_total_price',
            new_name='pre_amount',
        ),
    ]
