# Generated by Django 2.0 on 2018-08-28 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180821_1407'),
        ('projects', '0004_auto_20180828_1108'),
    ]

    operations = [
    ]
