# Generated by Django 2.0 on 2018-06-25 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180622_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMilestonesChangedRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Milestone', verbose_name='里程碑节点')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectPlan', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目里程碑项变更记录',
                'verbose_name_plural': '项目里程碑项变更记录',
                'db_table': 'projects_milestone_changed_record',
            },
        ),
        migrations.AddField(
            model_name='projectplan',
            name='milestones',
            field=models.ManyToManyField(blank=True, related_name='projects', related_query_name='project', through='projects.ProjectMilestonesChangedRecord', to='projects.Milestone', verbose_name='里程碑轨迹'),
        ),
    ]
