# Generated by Django 2.0 on 2018-08-29 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_merge_20180828_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=80, verbose_name='文档名称')),
                ('category', models.CharField(max_length=30, verbose_name='文档类别')),
                ('path', models.CharField(max_length=255, verbose_name='存放路径')),
            ],
            options={
                'verbose_name': '文档资料',
                'verbose_name_plural': '文档资料',
                'db_table': 'projects_project_document',
            },
        ),
        migrations.CreateModel(
            name='PurchaseContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('contract_no', models.CharField(max_length=30, verbose_name='合同编号')),
                ('title', models.CharField(max_length=100, verbose_name='合同名称')),
                ('signed_date', models.DateField(verbose_name='签订时间')),
                ('buyer', models.CharField(max_length=128, verbose_name='买方/甲方单位')),
                ('buyer_contact', models.CharField(max_length=50, verbose_name='买方/甲方联系人')),
                ('buyer_tel', models.CharField(max_length=11, verbose_name='买方/甲方联系电话')),
                ('seller', models.CharField(max_length=128, verbose_name='卖方/乙方单位')),
                ('seller_contact', models.CharField(max_length=50, verbose_name='卖方/乙方联系人')),
                ('seller_tel', models.CharField(max_length=11, verbose_name='卖方/乙方联系电话')),
                ('total_amount', models.FloatField(default=0.0, verbose_name='合同总价')),
                ('delivery_date', models.DateField(verbose_name='交货时间')),
                ('doc_list', models.CharField(blank=True, max_length=20, null=True, verbose_name='合同文档列表')),
            ],
            options={
                'verbose_name': '采购合同',
                'verbose_name_plural': '采购合同',
                'db_table': 'projects_purchase_contract',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('served_date', models.DateField(verbose_name='到货时间')),
                ('delivery_man', models.CharField(max_length=50, verbose_name='送货人')),
                ('contact_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='联系电话')),
                ('doc_list', models.CharField(blank=True, max_length=10, null=True, verbose_name='送货单附件')),
            ],
            options={
                'verbose_name': '收货确认单',
                'verbose_name_plural': '收货确认单',
                'db_table': 'projects_receipt',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=100, verbose_name='供应商名称')),
                ('contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系人')),
                ('contact_tel', models.CharField(blank=True, max_length=12, null=True, verbose_name='联系电话')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'db_table': 'projects_supplier',
            },
        ),
        migrations.CreateModel(
            name='SupplierSelectionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('total_amount', models.FloatField(default=0.0, verbose_name='方案总价')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('doc_list', models.CharField(blank=True, max_length=32, null=True, verbose_name='方案文档列表')),
                ('selected', models.BooleanField(default=False, verbose_name='是否为最终选定方案')),
            ],
            options={
                'verbose_name': '供应商选择方案',
                'verbose_name_plural': '供应商选择方案',
                'db_table': 'projects_supplier_selection_plan',
            },
        ),
        migrations.AlterField(
            model_name='projectmilestonerecord',
            name='summary',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='总结说明'),
        ),
        migrations.AddField(
            model_name='supplierselectionplan',
            name='project_milestone_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectMilestoneRecord', verbose_name='所属项目里程碑子节点'),
        ),
        migrations.AddField(
            model_name='supplierselectionplan',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Supplier', verbose_name='供应商'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='project_milestone_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectMilestoneRecord', verbose_name='所属项目里程碑子节点'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='project_milestone_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectMilestoneRecord', verbose_name='所属项目里程碑子节点'),
        ),
    ]
