# Generated by Django 2.0 on 2018-06-25 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20180625_1430'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectMilestonesChangedRecord',
            new_name='ProjectMilestoneRecord',
        ),
        migrations.AlterModelOptions(
            name='projectmilestonerecord',
            options={'verbose_name': '项目里程碑记录', 'verbose_name_plural': '项目里程碑记录'},
        ),
    ]
