# Generated by Django 2.0 on 2018-08-28 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20180828_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='flow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.ProjectFlow', verbose_name='归属流程'),
        ),
    ]
