# Generated by Django 2.0 on 2018-06-25 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20180625_1520'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projectmilestonerecord',
            table='projects_project_milestone_record',
        ),
    ]
