# Generated by Django 2.0 on 2018-08-29 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20180829_1024'),
        ('projects', '0006_auto_20180828_1620'),
    ]

    operations = [
    ]
