# Generated by Django 2.0 on 2018-08-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_merge_20180829_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectOperationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.IntegerField(verbose_name='项目')),
                ('reason', models.TextField(verbose_name='原因')),
                ('operation', models.CharField(choices=[('overrule', '驳回'), ('pause', '挂起')], max_length=10, verbose_name='操作方式')),
            ],
            options={
                'verbose_name': '项目操作日志',
                'verbose_name_plural': '项目操作日志',
                'db_table': 'projects_operation_record',
            },
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='status',
            field=models.CharField(choices=[('PE', '未开始'), ('SD', '已启动'), ('DO', '已完成'), ('OR', '已驳回'), ('PA', '已挂起')], default='PE', max_length=2, verbose_name='项目状态'),
        ),
    ]
