# Generated by Django 2.0 on 2018-07-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20180625_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectplan',
            name='handing_type',
            field=models.CharField(choices=[('SE', '自行办理'), ('AG', '转交办理')], default='SE', max_length=2, verbose_name='申请类型'),
        ),
    ]
