# Generated by Django 2.0 on 2018-07-04 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_auto_20180622_1804'),
        ('projects', '0008_projectplan_handing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectplan',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_projects', to='hospitals.Staff', verbose_name='协助办理人'),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='handing_type',
            field=models.CharField(choices=[('SE', '自行办理'), ('AG', '转交办理')], default='SE', max_length=2, verbose_name='办理方式'),
        ),
    ]
