# Generated by Django 2.0 on 2018-08-30 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20180829_1802'),
        ('projects', '0008_auto_20180829_1628'),
    ]

    operations = [
    ]
