# Generated by Django 2.0 on 2018-07-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20180704_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectplan',
            name='project_cate',
            field=models.CharField(choices=[('SW', '信息化软件项目'), ('HW', '信息化硬件项目')], default='HW', max_length=2, verbose_name='项目类型'),
        ),
    ]
