# Generated by Django 2.0 on 2018-08-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_merge_20180830_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectflow',
            name='default_flow',
            field=models.BooleanField(default=True, verbose_name='是否为默认流程'),
        ),
    ]
