# Generated by Django 2.0 on 2018-07-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_projectplan_project_cate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectplan',
            name='project_cate',
            field=models.CharField(choices=[('SW', '信息化项目'), ('HW', '医疗器械项目')], default='HW', max_length=2, verbose_name='项目类型'),
        ),
    ]
