# Generated by Django 2.0 on 2018-08-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20180830_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmilestonerecord',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='节点任务是否完结'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='category',
            field=models.CharField(choices=[('product', '产品资料'), ('producer', '厂商资料'), ('supplier_selection_plan', '供应商选择方案'), ('plan_argument', '方案论证资料'), ('decision_argument', '决策论证'), ('bidding_doc', '招标文件'), ('tender_doc', '投标文件'), ('purchase_plan', '采购计划'), ('contract', '合同'), ('delivery_note', '送货单'), ('implement_plan', '实施方案'), ('implement_record', '实施日志'), ('implement_summary', '实施总结'), ('acceptance_plan', '验收方案'), ('acceptance_report', '验收报告'), ('others', '其他资料')], max_length=30, verbose_name='文档类别'),
        ),
        migrations.AlterField(
            model_name='projectflow',
            name='default_flow',
            field=models.BooleanField(default=False, verbose_name='是否为默认流程'),
        ),
    ]
