# Generated by Django 2.0 on 2018-09-03 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20180831_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='parent_path',
            field=models.CharField(default='', max_length=1024, verbose_name='父里程碑路径'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Milestone', verbose_name='父里程碑'),
        ),
    ]
