# Generated by Django 2.0 on 2018-09-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20180903_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectplan',
            name='procurement_method',
            field=models.CharField(blank=True, choices=[('OPEN', '公招招标'), ('INVITED', '邀请招标/选择性招标'), ('COMPETITIVE', '竞争性谈判/协商招标'), ('SINGE', '单一来源采购'), ('INQUIRY', '询价采购')], max_length=20, null=True, verbose_name='采购方式'),
        ),
    ]
