# Generated by Django 2.0 on 2018-09-04 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20180903_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectplan',
            old_name='procurement_method',
            new_name='purchase_method',
        ),
    ]
