# Generated by Django 2.0 on 2018-09-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20180904_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmilestonerecord',
            name='finished',
        ),
        migrations.AddField(
            model_name='projectmilestonerecord',
            name='status',
            field=models.CharField(choices=[('TODO', '未开始'), ('DOING', '进行中'), ('DONE', '已完结')], default='TODO', max_length=10, verbose_name='项目里程碑状态'),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='purchase_method',
            field=models.CharField(blank=True, choices=[('OPEN', '公开招标'), ('INVITED', '邀请招标/选择性招标'), ('COMPETITIVE', '竞争性谈判/协商招标'), ('SINGE', '单一来源采购'), ('INQUIRY', '询价采购')], max_length=20, null=True, verbose_name='采购方式'),
        ),
    ]
