# Generated by Django 2.0 on 2018-09-13 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20180910_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMilestoneState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('doc_list', models.CharField(blank=True, max_length=100, null=True, verbose_name='文档列表')),
                ('summary', models.TextField(blank=True, max_length=200, null=True, verbose_name='总结说明')),
                ('status', models.CharField(choices=[('TODO', '未开始'), ('DOING', '进行中'), ('DONE', '已完结')], default='TODO', max_length=10, verbose_name='项目里程碑状态')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pro_milestone_states_related', to='projects.Milestone', verbose_name='里程碑节点')),
            ],
            options={
                'verbose_name': '项目里程碑',
                'verbose_name_plural': '项目里程碑',
                'db_table': 'projects_project_milestone_state',
            },
        ),
        migrations.RemoveField(
            model_name='projectmilestonerecord',
            name='milestone',
        ),
        migrations.RemoveField(
            model_name='projectmilestonerecord',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectplan',
            name='milestones',
        ),
        migrations.RemoveField(
            model_name='purchasecontract',
            name='project_milestone_record',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='project_milestone_record',
        ),
        migrations.RemoveField(
            model_name='supplierselectionplan',
            name='project_milestone_record',
        ),
        migrations.DeleteModel(
            name='ProjectMilestoneRecord',
        ),
        migrations.AddField(
            model_name='projectmilestonestate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_milestone_states_related', to='projects.ProjectPlan', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='projectplan',
            name='pro_milestone_states',
            field=models.ManyToManyField(blank=True, related_name='projects', related_query_name='project', through='projects.ProjectMilestoneState', to='projects.Milestone', verbose_name='项目里程碑'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='project_milestone_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectMilestoneState', verbose_name='所属项目里程碑子节点'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='project_milestone_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectMilestoneState', verbose_name='所属项目里程碑子节点'),
        ),
        migrations.AddField(
            model_name='supplierselectionplan',
            name='project_milestone_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectMilestoneState', verbose_name='所属项目里程碑子节点'),
        ),
        migrations.AlterUniqueTogether(
            name='projectmilestonestate',
            unique_together={('project', 'milestone')},
        ),
    ]
