# Generated by Django 2.0 on 2018-10-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_projectmilestonestate_finished_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmilestonestate',
            name='modified_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='最近一次修改时间'),
        ),
    ]
