# Generated by Django 2.0 on 2018-10-30 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_projectmilestonestate_modified_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['index'], 'permissions': (('view_milestone', 'can view milestone'),), 'verbose_name': '里程碑项', 'verbose_name_plural': '里程碑项'},
        ),
        migrations.AlterModelOptions(
            name='projectflow',
            options={'permissions': (('view_project_flow', 'can view project flow'),), 'verbose_name': 'B 项目流程', 'verbose_name_plural': 'B 项目流程'},
        ),
        migrations.AlterModelOptions(
            name='projectmilestonestate',
            options={'permissions': (('view_project_milestone_state', 'can view project milestone state'),), 'verbose_name': '项目里程碑', 'verbose_name_plural': '项目里程碑'},
        ),
        migrations.AlterModelOptions(
            name='projectoperationrecord',
            options={'permissions': (('view_project_operation_record', 'can view project operation record'),), 'verbose_name': '项目操作日志', 'verbose_name_plural': '项目操作日志'},
        ),
        migrations.AlterModelOptions(
            name='projectplan',
            options={'permissions': (('view_project_plan', 'can view project plan'), ('dispatch_project_plan', 'can dispatch project plan'), ('overrule_project_plan', 'can overrule project plan'), ('pause_project_plan', 'can pause project plan'), ('startup_project_plan', 'can startup project plan')), 'verbose_name': 'A 项目申请', 'verbose_name_plural': 'A 项目申请'},
        ),
        migrations.AlterModelOptions(
            name='purchasecontract',
            options={'permissions': (('view_purchase_contract', 'can view supplier purchase contract'),), 'verbose_name': '采购合同', 'verbose_name_plural': '采购合同'},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'permissions': (('view_receipt', 'can view receipt'),), 'verbose_name': '收货确认单', 'verbose_name_plural': '收货确认单'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'permissions': (('view_supplier', 'can view supplier'),), 'verbose_name': '供应商', 'verbose_name_plural': '供应商'},
        ),
        migrations.AlterModelOptions(
            name='supplierselectionplan',
            options={'permissions': (('view_supplier_selection_plan', 'can view supplier selection plan'),), 'verbose_name': '供应商选择方案', 'verbose_name_plural': '供应商选择方案'},
        ),
    ]
