# Generated by Django 2.0 on 2018-11-07 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20181030_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectplan',
            name='finished_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='项目实际完结时间'),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='current_stone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.ProjectMilestoneState', verbose_name='项目里程碑节点'),
        ),
    ]
