# Generated by Django 2.0 on 2018-11-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20181107_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmilestonestate',
            name='modified_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='最近一次修改时间'),
        ),
    ]
