# Generated by Django 2.0 on 2018-06-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=30, verbose_name='设备名称')),
                ('cate', models.CharField(blank=True, max_length=10, null=True, verbose_name='设备类别')),
                ('producer', models.CharField(blank=True, max_length=30, null=True, verbose_name='设备生产者')),
                ('planned_price', models.FloatField(default=0.0, verbose_name='预算单价')),
                ('real_price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='实际单价')),
                ('num', models.IntegerField(default=1, verbose_name='预购数量')),
                ('measure', models.CharField(blank=True, max_length=5, null=True, verbose_name='度量/单位')),
                ('type_spec', models.CharField(blank=True, max_length=20, null=True, verbose_name='规格/型号')),
                ('purpose', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='用途')),
            ],
            options={
                'verbose_name': '申购的设备',
                'verbose_name_plural': '申购的设备',
                'db_table': 'devices_ordered_device',
            },
        ),
    ]
