# Generated by Django 2.0 on 2018-06-08 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereddevice',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectPlan', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='ordereddevice',
            name='cate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='设备类型'),
        ),
    ]
