# Generated by Django 2.0 on 2018-08-21 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20180724_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordereddevice',
            options={'verbose_name': '申购的硬件设备', 'verbose_name_plural': '申购的硬件设备'},
        ),
        migrations.AlterModelOptions(
            name='softwaredevice',
            options={'verbose_name': '申购的软件设备', 'verbose_name_plural': '申购的软件设备'},
        ),
        migrations.AlterField(
            model_name='ordereddevice',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_devices', to='projects.ProjectPlan', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='softwaredevice',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='software_devices', to='projects.ProjectPlan', verbose_name='所属项目'),
        ),
    ]
