# Generated by Django 2.0 on 2018-08-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20180828_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwaredevice',
            name='planned_price',
            field=models.FloatField(default=0.0, verbose_name='预算单价'),
        ),
        migrations.AddField(
            model_name='softwaredevice',
            name='real_price',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='实际单价'),
        ),
    ]
