# Generated by Django 2.0 on 2018-08-28 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20180821_1407'),
        ('devices', '0003_auto_20180828_1058'),
    ]

    operations = [
    ]
