# Generated by Django 2.0 on 2018-08-29 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20180829_1024'),
        ('devices', '0004_merge_20180828_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=30, verbose_name='设备名称')),
                ('cate', models.CharField(blank=True, max_length=10, null=True, verbose_name='设备类型')),
                ('producer', models.CharField(blank=True, max_length=30, null=True, verbose_name='设备生产者')),
                ('supplier', models.CharField(blank=True, max_length=100, null=True, verbose_name='供应商')),
                ('planned_price', models.FloatField(default=0.0, verbose_name='预算单价')),
                ('real_price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='实际单价')),
                ('num', models.IntegerField(default=1, verbose_name='预购数量')),
                ('real_total_amount', models.FloatField(blank=True, default=0.0, null=True, verbose_name='总价')),
                ('measure', models.CharField(blank=True, max_length=5, null=True, verbose_name='度量/单位')),
                ('type_spec', models.CharField(blank=True, max_length=20, null=True, verbose_name='规格/型号')),
                ('purpose', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='用途')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_devices', to='projects.PurchaseContract', verbose_name='所属采购合同')),
            ],
            options={
                'verbose_name': '采购合同产品明细',
                'verbose_name_plural': '采购合同产品明细',
                'db_table': 'devices_contract_device',
            },
        ),
    ]
