# Generated by Django 2.0 on 2018-11-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20181130_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldevicecate',
            name='desc',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='产品分类描述'),
        ),
        migrations.AddField(
            model_name='medicaldevicecate',
            name='purpose',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='预期用途'),
        ),
        migrations.AlterField(
            model_name='medicaldevicecate',
            name='mgt_cate',
            field=models.SmallIntegerField(choices=[(1, 'Ⅰ'), (2, 'Ⅱ'), (3, 'Ⅲ')], null=True, verbose_name='管理类别'),
        ),
    ]
