# Generated by Django 2.0 on 2018-08-29 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20180828_1400'),
        ('devices', '0005_contractdevice'),
    ]

    operations = [
    ]
