# Generated by Django 2.0 on 2018-10-16 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_auto_20181016_1342'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medicaldevicesix8cate',
            table='devices_medical_device_six8_cate',
        ),
    ]
