# Generated by Django 2.0 on 2018-10-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_auto_20181017_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repairorder',
            name='status',
            field=models.CharField(choices=[('SMT', '已提交/待分派'), ('DNG', '处理中/已分派'), ('DNE', '已处理'), ('RTN', '已退回'), ('CLS', '已关闭')], default='SMT', max_length=3, verbose_name='状态'),
        ),
    ]
