# Generated by Django 2.0 on 2018-10-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_auto_20181019_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faultsolution',
            name='doc_list',
        ),
        migrations.RemoveField(
            model_name='repairorder',
            name='doc_list',
        ),
        migrations.AddField(
            model_name='faultsolution',
            name='files',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='附件列表'),
        ),
        migrations.AddField(
            model_name='repairorder',
            name='files',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='附件列表'),
        ),
    ]
