# Generated by Django 2.0 on 2018-10-20 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_auto_20181020_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repairorder',
            old_name='assert_devices',
            new_name='repair_devices',
        ),
    ]
