# Generated by Django 2.0 on 2018-10-29 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_auto_20181020_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assertdevice',
            options={'permissions': (('view_assert_device', 'can view assert devices'), ('scrap_assert_device', 'can scrap assert devices'), ('allocate_assert_device', 'can allocate assert devices')), 'verbose_name': '资产设备', 'verbose_name_plural': '资产设备'},
        ),
    ]
