# Generated by Django 2.0 on 2018-10-29 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_auto_20181020_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assertdevice',
            name='medical_device_cate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_assert_device', to='devices.MedicalDeviceSix8Cate', verbose_name='医疗器械分类'),
        ),
    ]
