# Generated by Django 2.0 on 2018-10-30 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_auto_20181029_1731'),
        ('devices', '0013_auto_20181029_1118'),
    ]

    operations = [
    ]
