# Generated by Django 2.0 on 2018-10-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0014_merge_20181030_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faulttype',
            options={'verbose_name': '故障类型', 'verbose_name_plural': '故障类型'},
        ),
        migrations.AlterField(
            model_name='medicaldevicesix8cate',
            name='mgt_cate',
            field=models.SmallIntegerField(null=True, verbose_name='管理类别'),
        ),
    ]
