# Generated by Django 2.0 on 2018-10-31 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0015_auto_20181030_1525'),
        ('devices', '0015_auto_20181030_1542'),
    ]

    operations = [
    ]
