# Generated by Django 2.0 on 2018-11-07 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0016_merge_20181031_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faultsolution',
            options={'permissions': (('view_fault_solution', 'can view fault solution'), ('import_fault_solution', 'can import fault solution'), ('export_fault_solution', 'can export fault solution'), ('audit_fault_solution', 'can audit fault solution')), 'verbose_name': '故障/问题解决方案', 'verbose_name_plural': '故障/问题解决方案'},
        ),
        migrations.AlterModelOptions(
            name='repairorder',
            options={'ordering': ['id'], 'permissions': (('view_repair_order', 'can view repair order'), ('dispatch_repair_order', 'can dispatch repair order')), 'verbose_name': '报修单/维修工单', 'verbose_name_plural': '报修单/维修工单'},
        ),
    ]
