# Generated by Django 2.0 on 2018-06-06 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('name', models.CharField(default='', max_length=100, verbose_name='部门名称')),
                ('contact', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='联系电话')),
                ('desc', models.TextField(blank=True, default='', null=True, verbose_name='描述')),
                ('attri', models.CharField(blank=True, choices=[('ME', '医技'), ('SU', '后勤'), ('OF', '行政')], max_length=2, null=True, verbose_name='科室/部门属性')),
            ],
            options={
                'verbose_name': 'A 科室/部门',
                'verbose_name_plural': 'A 科室/部门',
                'db_table': 'hosp_department',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=40, verbose_name='权限组名')),
                ('cate', models.CharField(blank=True, max_length=4, null=True, verbose_name='权限组类别')),
                ('is_admin', models.BooleanField(default=False, verbose_name='管理员组')),
                ('desc', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '权限组',
                'verbose_name_plural': '权限组',
                'db_table': 'perm_group',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('organ_name', models.CharField(default='', max_length=100, verbose_name='企业/组织名称')),
                ('organ_scale', models.SmallIntegerField(blank=True, choices=[(1, '0-49人'), (2, '50-199人'), (3, '200-499人'), (4, '500-999人'), (5, '1000-1999人'), (6, '2000人以上')], default=1, null=True, verbose_name='企业规模')),
                ('contact_name', models.CharField(default='', max_length=32, verbose_name='联系人姓名')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='联系人手机号码')),
                ('contact_title', models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='联系人职位')),
                ('logo', models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='企业logo')),
                ('industry', models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='行业类型')),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='企业/机构地址')),
                ('contact', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='联系电话')),
                ('auth_status', models.SmallIntegerField(choices=[(1, '等待审核'), (2, '审核通过'), (3, '审核未通过')], default=1, verbose_name='认证状态')),
                ('media_cover', models.CharField(blank=True, default='', max_length=800, null=True, verbose_name='媒体报道')),
                ('desc', models.TextField(blank=True, default='', null=True, verbose_name='企业介绍')),
                ('grade', models.CharField(blank=True, choices=[('3a', '三级甲等'), ('3b', '三级乙等'), ('3c', '三级丙等'), ('2a', '二级甲等'), ('2b', '二级乙等'), ('2c', '二级丙等')], default='', max_length=10, null=True, verbose_name='分类等级')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitals.Hospital', verbose_name='上级医疗单位')),
            ],
            options={
                'verbose_name': 'A 医疗机构',
                'verbose_name_plural': 'A 医疗机构',
                'db_table': 'hosp_hospital',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('name', models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='名字')),
                ('title', models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='职位名称')),
                ('contact', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Email')),
                ('status', models.CharField(default='N', max_length=1, verbose_name='员工状态')),
            ],
            options={
                'verbose_name': 'B 员工',
                'verbose_name_plural': 'B 员工',
                'db_table': 'hosp_staff',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('staff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hospitals.Staff')),
                ('medical_title', models.CharField(blank=True, choices=[('CF', '主任医生'), ('VCF', '副主任医生'), ('AT', '主治医生'), ('RE', '住院医生')], max_length=3, null=True, verbose_name='医生职称')),
            ],
            options={
                'verbose_name': 'D 医生',
                'verbose_name_plural': 'D 医生',
                'db_table': 'hosp_doctor',
            },
            bases=('hospitals.staff',),
        ),
        migrations.AddField(
            model_name='staff',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitals.Department', verbose_name='所属科室/部门'),
        ),
        migrations.AddField(
            model_name='staff',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitals.Group', verbose_name='权限组'),
        ),
        migrations.AddField(
            model_name='staff',
            name='organ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitals.Hospital', verbose_name='所属医院'),
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户账号'),
        ),
        migrations.AddField(
            model_name='group',
            name='organ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitals.Hospital', verbose_name='所属医院'),
        ),
        migrations.AddField(
            model_name='group',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='organs.Permission', verbose_name='权限集'),
        ),
        migrations.AddField(
            model_name='department',
            name='organ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.Hospital', verbose_name='所属医疗机构'),
        ),
    ]
