# Generated by Django 2.0 on 2018-11-19 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('name', models.CharField(default='', max_length=100, verbose_name='部门名称')),
                ('contact', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='联系电话')),
                ('desc', models.TextField(blank=True, default='', null=True, verbose_name='描述')),
                ('attri', models.CharField(blank=True, choices=[('ME', '医技'), ('SU', '后勤'), ('OF', '行政'), ('OT', '其他')], max_length=10, null=True, verbose_name='科室/部门属性')),
            ],
            options={
                'verbose_name': 'B 科室/部门',
                'verbose_name_plural': 'B 科室/部门',
                'db_table': 'hosp_department',
                'permissions': (('view_department', 'can view department'),),
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('organ_name', models.CharField(default='', max_length=100, verbose_name='企业/组织名称')),
                ('organ_scale', models.SmallIntegerField(blank=True, choices=[(1, '0-49人'), (2, '50-199人'), (3, '200-499人'), (4, '500-999人'), (5, '1000-1999人'), (6, '2000人以上')], default=1, null=True, verbose_name='企业规模')),
                ('contact_name', models.CharField(default='', max_length=32, verbose_name='联系人姓名')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='联系人手机号码')),
                ('contact_title', models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='联系人职位')),
                ('logo', models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='企业logo')),
                ('industry', models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='行业类型')),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='企业/机构地址')),
                ('contact', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='联系电话')),
                ('auth_status', models.SmallIntegerField(choices=[(1, '等待审核'), (2, '审核通过'), (3, '审核未通过')], default=1, verbose_name='认证状态')),
                ('media_cover', models.CharField(blank=True, default='', max_length=800, null=True, verbose_name='媒体报道')),
                ('desc', models.TextField(blank=True, default='', null=True, verbose_name='企业介绍')),
                ('grade', models.CharField(blank=True, choices=[('3a', '三级甲等'), ('3b', '三级乙等'), ('3c', '三级丙等'), ('2a', '二级甲等'), ('2b', '二级乙等'), ('2c', '二级丙等')], default='', max_length=10, null=True, verbose_name='分类等级')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitals.Hospital', verbose_name='上级医疗单位')),
            ],
            options={
                'verbose_name': 'A 医疗机构',
                'verbose_name_plural': 'A 医疗机构',
                'db_table': 'hosp_hospital',
                'permissions': (('view_hospital', 'can view hospital'),),
            },
        ),
        migrations.CreateModel(
            name='HospitalAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('title', models.CharField(max_length=128, verbose_name='名称')),
                ('type', models.CharField(choices=[('BD', '楼'), ('RM', '房间')], max_length=10, verbose_name='类型')),
                ('parent_path', models.CharField(default='', max_length=255, verbose_name='父地址路径')),
                ('level', models.SmallIntegerField(verbose_name='层级')),
                ('sort', models.SmallIntegerField(verbose_name='排序')),
                ('disabled', models.BooleanField(default=False, verbose_name='是否禁用')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hospitals.Department', verbose_name='所属科室')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hospitals.HospitalAddress', verbose_name='父级地址')),
            ],
            options={
                'verbose_name': 'G 医院内部地址',
                'verbose_name_plural': 'G 医院内部地址',
                'db_table': 'hosp_hospital_address',
                'permissions': (('view_hospital_address', 'can view hospital address'),),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='角色名称')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='角色代码')),
                ('cate', models.CharField(choices=[('CNM', '普通角色类')], default='CNM', max_length=10, verbose_name='类别')),
                ('desc', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='描述')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', related_query_name='role', to='auth.Permission', verbose_name='权限集')),
            ],
            options={
                'verbose_name': 'E 角色管理',
                'verbose_name_plural': 'E 角色管理',
                'db_table': 'perm_role',
                'permissions': (('view_role', 'can view role'), ('assign_role', 'can assign role')),
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('seq_code', models.CharField(max_length=20, unique=True, verbose_name='sequence编码')),
                ('seq_name', models.CharField(max_length=64, verbose_name='sequence编码名称')),
                ('seq_value', models.IntegerField(default=0, verbose_name='sequence值')),
                ('increment', models.IntegerField(default=1, verbose_name='步进')),
                ('remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'H 序列管理',
                'verbose_name_plural': 'H 序列管理',
                'db_table': 'hosp_sequence',
                'permissions': (('view_sequence', 'can view sequence'),),
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('name', models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='名字')),
                ('title', models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='职位名称')),
                ('contact', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Email')),
                ('status', models.CharField(default='N', max_length=1, verbose_name='员工状态')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
            ],
            options={
                'verbose_name': 'C 员工',
                'verbose_name_plural': 'C 员工',
                'db_table': 'hosp_staff',
                'permissions': (('view_staff', 'can view staff'), ('import_staff', 'can import staff')),
            },
        ),
        migrations.CreateModel(
            name='UserRoleShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('dept_domains', models.ManyToManyField(blank=True, related_name='user_role_ships', related_query_name='user_role_ship', to='hospitals.Department', verbose_name='用户当前角色可操作部门域集合')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_ships', to='hospitals.Role', verbose_name='角色')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_ships', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'F 用户角色关系',
                'verbose_name_plural': 'F 用户角色关系',
                'db_table': 'perm_user_roles',
                'permissions': (('view_user_role_ship', 'can view user role ship'),),
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('staff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hospitals.Staff')),
                ('medical_title', models.CharField(blank=True, choices=[('CF', '主任医生'), ('VCF', '副主任医生'), ('AT', '主治医生'), ('RE', '住院医生')], max_length=10, null=True, verbose_name='医生职称')),
            ],
            options={
                'verbose_name': 'D 医生',
                'verbose_name_plural': 'D 医生',
                'db_table': 'hosp_doctor',
                'permissions': (('view_doctor', 'can view doctor'),),
            },
            bases=('hospitals.staff',),
        ),
        migrations.AddField(
            model_name='staff',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitals.Department', verbose_name='所属科室/部门'),
        ),
        migrations.AddField(
            model_name='staff',
            name='organ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitals.Hospital', verbose_name='所属医院'),
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户账号'),
        ),
        migrations.AddField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='roles', related_query_name='role', through='hospitals.UserRoleShip', to=settings.AUTH_USER_MODEL, verbose_name='角色所属用户集'),
        ),
        migrations.AddField(
            model_name='department',
            name='organ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organ', to='hospitals.Hospital', verbose_name='所属医疗机构'),
        ),
        migrations.AlterUniqueTogether(
            name='userroleship',
            unique_together={('user', 'role')},
        ),
    ]
