# Generated by Django 2.0 on 2018-07-24 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=40, verbose_name='角色名称')),
                ('codename', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='角色代码')),
                ('cate', models.CharField(blank=True, choices=[('GPA', '项目分配人'), ('GNS', '普通员工'), ('GCR', '角色类'), ('GCU', '用户类')], max_length=4, verbose_name='类别')),
                ('desc', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'perm_role',
            },
        ),
        migrations.CreateModel(
            name='UserRoleShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户角色关系',
                'verbose_name_plural': '用户角色关系',
                'db_table': 'perm_user_roles',
            },
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'B 科室/部门', 'verbose_name_plural': 'B 科室/部门'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'C 员工', 'verbose_name_plural': 'C 员工'},
        ),
        migrations.AlterField(
            model_name='department',
            name='attri',
            field=models.CharField(blank=True, choices=[('ME', '医技'), ('SU', '后勤'), ('OF', '行政'), ('OT', '其他')], max_length=2, null=True, verbose_name='科室/部门属性'),
        ),
        migrations.AlterField(
            model_name='department',
            name='organ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organ', to='hospitals.Hospital', verbose_name='所属医疗机构'),
        ),
        migrations.AlterField(
            model_name='group',
            name='cate',
            field=models.CharField(blank=True, choices=[('GPA', '项目分配人'), ('GNS', '普通员工'), ('GCR', '角色类'), ('GCU', '用户类')], max_length=4, null=True, verbose_name='权限组类别'),
        ),
        migrations.AddField(
            model_name='userroleship',
            name='dept_domains',
            field=models.ManyToManyField(blank=True, related_name='UserRoleShips', related_query_name='UserRoleShip', to='hospitals.Department', verbose_name='用户当前角色可操作部门域集合'),
        ),
        migrations.AddField(
            model_name='userroleship',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.Role', verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='userroleship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', related_query_name='role', to='hospitals.Group', verbose_name='权限集'),
        ),
        migrations.AddField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='roles', related_query_name='role', through='hospitals.UserRoleShip', to=settings.AUTH_USER_MODEL, verbose_name='角色所属用户集'),
        ),
        migrations.AlterUniqueTogether(
            name='userroleship',
            unique_together={('user', 'role')},
        ),
    ]
