# Generated by Django 2.0 on 2018-06-22 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'B 科室/部门', 'verbose_name_plural': 'B 科室/部门'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'C 员工', 'verbose_name_plural': 'C 员工'},
        ),
        migrations.AlterField(
            model_name='department',
            name='attri',
            field=models.CharField(blank=True, choices=[('ME', '医技'), ('SU', '后勤'), ('OF', '行政'), ('OT', '其他')], max_length=2, null=True, verbose_name='科室/部门属性'),
        ),
        migrations.AlterField(
            model_name='department',
            name='organ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organ', to='hospitals.Hospital', verbose_name='所属医疗机构'),
        ),
        migrations.AlterField(
            model_name='group',
            name='cate',
            field=models.CharField(blank=True, choices=[('GPA', '项目分配人'), ('GNS', '普通员工')], max_length=4, null=True, verbose_name='权限组类别'),
        ),
    ]
