# Generated by Django 2.0 on 2018-11-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitaladdress',
            name='type',
        ),
        migrations.AddField(
            model_name='hospitaladdress',
            name='is_storage_place',
            field=models.BooleanField(default=False, verbose_name='是否存储地点'),
        ),
    ]
