# Generated by Django 2.0 on 2018-11-30 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_auto_20181128_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaladdress',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_addresses', to='hospitals.Staff', verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='hospitaladdress',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hospitals.Hospital', verbose_name='所属医院'),
        ),
        migrations.AddField(
            model_name='hospitaladdress',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='hospitaladdress',
            name='modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_addresses', to='hospitals.Staff', verbose_name='修改人'),
        ),
    ]
