# Generated by Django 2.0 on 2018-07-18 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospitals', '0002_auto_20180622_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=40, verbose_name='角色名称')),
                ('codename', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='角色代码')),
                ('cate', models.CharField(blank=True, choices=[('GPA', '项目分配人'), ('GNS', '普通员工'), ('GCR', '角色类'), ('GCU', '用户类')], max_length=4, verbose_name='类别')),
                ('desc', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='描述')),
                ('departments', models.ManyToManyField(blank=True, related_name='roles', related_query_name='role', to='hospitals.Department', verbose_name='所属部门集合')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'perm_role',
            },
        ),
        migrations.AlterField(
            model_name='group',
            name='cate',
            field=models.CharField(blank=True, choices=[('GPA', '项目分配人'), ('GNS', '普通员工'), ('GCR', '角色类'), ('GCU', '用户类')], max_length=4, null=True, verbose_name='权限组类别'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='hospitals.Group', verbose_name='权限集'),
        ),
        migrations.AddField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='roles', related_query_name='role', to=settings.AUTH_USER_MODEL, verbose_name='所属用户集合'),
        ),
    ]
