# Generated by Django 2.0 on 2018-08-21 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_auto_20180724_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'permissions': (('view_staff', 'can view staffs'),), 'verbose_name': 'C 员工', 'verbose_name_plural': 'C 员工'},
        ),
        migrations.AlterField(
            model_name='userroleship',
            name='dept_domains',
            field=models.ManyToManyField(blank=True, related_name='user_role_ships', related_query_name='user_role_ship', to='hospitals.Department', verbose_name='用户当前角色可操作部门域集合'),
        ),
        migrations.AlterField(
            model_name='userroleship',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_ships', to='hospitals.Role', verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='userroleship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_ships', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
