# Generated by Django 2.0 on 2018-07-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_auto_20180718_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='departments',
            new_name='dept_domains',
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', related_query_name='role', to='hospitals.Group', verbose_name='权限集'),
        ),
    ]
