# Generated by Django 2.0 on 2018-10-16 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_hospitaladdress'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hospitaladdress',
            table='hosp_hospital_address',
        ),
    ]
