# Generated by Django 2.0 on 2018-10-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0006_auto_20181016_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('seq_name', models.CharField(max_length=16, unique=True, verbose_name='sequence标识')),
                ('seq_value', models.IntegerField(default=1, verbose_name='当前sequence值')),
                ('increment', models.IntegerField(default=1, verbose_name='步进')),
                ('comment', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '序列',
                'verbose_name_plural': '序列',
                'db_table': 'hosp_sequence',
            },
        ),
    ]
