# Generated by Django 2.0 on 2018-10-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0007_sequence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequence',
            old_name='comment',
            new_name='remark',
        ),
        migrations.AddField(
            model_name='sequence',
            name='seq_code',
            field=models.CharField(default='2', max_length=16, unique=True, verbose_name='sequence编码'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='seq_name',
            field=models.CharField(max_length=64, verbose_name='sequence编码名称'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='seq_value',
            field=models.IntegerField(default=1, verbose_name='sequence值'),
        ),
    ]
