# Generated by Django 2.0 on 2018-10-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0009_auto_20181019_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '角色管理', 'verbose_name_plural': '角色管理'},
        ),
        migrations.AlterField(
            model_name='role',
            name='cate',
            field=models.CharField(choices=[('RCNM', '普通角色类')], default='RCNM', max_length=4, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='role',
            name='codename',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='角色代码'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', related_query_name='role', to='auth.Permission', verbose_name='权限集'),
        ),
    ]
