# Generated by Django 2.0 on 2018-10-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0010_auto_20181029_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'permissions': (('view_department', 'can view department'),), 'verbose_name': 'B 科室/部门', 'verbose_name_plural': 'B 科室/部门'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'permissions': (('view_doctor', 'can view doctor'),), 'verbose_name': 'D 医生', 'verbose_name_plural': 'D 医生'},
        ),
        migrations.AlterModelOptions(
            name='hospital',
            options={'permissions': (('view_hospital', 'can view hospital'),), 'verbose_name': 'A 医疗机构', 'verbose_name_plural': 'A 医疗机构'},
        ),
        migrations.AlterModelOptions(
            name='hospitaladdress',
            options={'permissions': (('view_hospital_address', 'can view hospital address'),), 'verbose_name': 'G 医院内部地址', 'verbose_name_plural': 'G 医院内部地址'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'permissions': (('view_role', 'can view role'), ('assign_role', 'can assign role')), 'verbose_name': 'E 角色管理', 'verbose_name_plural': 'E 角色管理'},
        ),
        migrations.AlterModelOptions(
            name='sequence',
            options={'permissions': (('view_sequence', 'can view sequence'),), 'verbose_name': 'H 序列管理', 'verbose_name_plural': 'H 序列管理'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'permissions': (('view_staff', 'can view staff'), ('import_staff', 'can import staff')), 'verbose_name': 'C 员工', 'verbose_name_plural': 'C 员工'},
        ),
        migrations.AlterModelOptions(
            name='userroleship',
            options={'permissions': (('view_user_role_ship', 'can view user role ship'),), 'verbose_name': 'F 用户角色关系', 'verbose_name_plural': 'F 用户角色关系'},
        ),
        migrations.AlterField(
            model_name='role',
            name='cate',
            field=models.CharField(choices=[('CNM', '普通角色类')], default='CNM', max_length=4, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='role',
            name='codename',
            field=models.CharField(max_length=100, unique=True, verbose_name='角色代码'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='角色名称'),
        ),
    ]
